mysql:
  host: localhost
  port: 3306
  database: economy
  username: sql
  password: secret
  max-pool-size: 12

messages:
  error-occurred: '&cAn error occurred when performing this command, please check console for more details.'
  not-loaded-yet: '&cYour data is not fully loaded yet, please wait...'
  command-perform-incomplete: '&cPlease wait until the previous command finishes performing...'
  player-not-found: '&cSorry, but we could not find a user matches the name &4{name}&c!'
  your-balance: '&eYour balance is &c${balance}&e.'
  others-balance: '&e{name}''s balance is &c%{balance}'
  insufficient-funds: '&cYou have insufficient funds!'
  payment-received: '&eYou''ve received a payment of &c${amount}&e from &c{player}&e!'
  payment-sent: '&eYou''ve paid &c{player}&e, we''ve removed &c${balance}&e from your wallet.'
  balance-updated: '&eSuccessfully updated balance of &c{player}&e to &c${balance}&e!'
  earn-cooldown: '&cPlease wait &4{time}&c seconds before you can earn again.'
  earned: '&eYou successfully earned &c${amount}&c, you can repeat this command after 60 seconds!'
